### ISSUE TITLE
Mobile swipe gestures not working.

### ISSUE THREAD

**Issue by ChrisPowellIinc** [BIVROST/360WebPlayer#10]
Can't change POV with touch drag on mobile.

**Comment by chanibal** [comment]
Hello, could you please provide some more details? 
1. What is your phone, OS and browser
2. Please provide the address of the page where you have seen the bug (check if the error occurs on the [demo page](https://tools.bivrost360.com/webplayer-docs/))
3. Did you press the big play button to make the player fullscreen? Fullscreen is needed for swipes and zoom to register.
4. By changing POV you mean looking around or zooming?

**Comment by ChrisPowellIinc** [comment]
Thanks for the prompt reply.  Is there a way to keep the zoom and swipe gesture without fullscreen?

**Comment by chanibal** [comment]
It was purposefully disabled. 

If it had not been, the user might easily gotten stuck on the player without any way to view the rest of the page.  
For example, the user scrolls to the player and then tries to scroll further down - but they cannot, because swiping rotates their 360 view and not scrolls down. And they cannot swipe outside of the player, because it might be (and often is) obscuring the whole viewport.

**Comment by ChrisPowellIinc** [comment]
Understood, however that would only happen if no margin was left on either side, above or below the player.  Could you please help me identify where in the JS to enable outside of fullscreen? Love the player, best on the market since omnivirt.

**Comment by ChrisPowellIinc** [comment]
I've got  use cases where I'd like it to be fully function within the UI.

**Comment by chanibal** [comment]
Looked around a bit, and I'm afraid that this change is not so easy.  

The change probably revolves around `player.fullscreen` checks in the input module, but I wasn't able to check this yet - and unfortunately these things require a lot of testing to get right.  
Not to mention that this ties to fullscreen support, and it is a bit complex (cardboard/legacy VR, hacky iOS support etc).

As this is more of a feature, than a bug, I must ask - are you in the free/personal use tier or is this licensed for commercial use?
