### ISSUE TITLE
Why iOS doesn't have HLS support?

### ISSUE THREAD

**Issue by amerllica** [BIVROST/360WebPlayer#3]
This library is awesome but for my solution, I seriously need to have support on iOS devices, especially iPhone, I don't see the source code, So I leave an issue to ask what's the main reason for this lack?

- Is this a bug?
- 360WebPlayer wasn't developed for iOS?
- Is it a technical issue from the base package?

**Comment by chanibal** [comment]
The original reason on why iOS does not support HLS is HLS.js not supporting that platform and native HLS not working with webgl properly. But it has been years I've stumbled upon this issue and while HLS.js still does not support iOS, maybe the native support can be used now. 
I'll need to verify this.

> I don't see the source code

The source code is available on this repository, in the [`src`](https://github.com/BIVROST/360WebPlayer/tree/master/src) directory with instructions on how to build the project in the [development document](https://github.com/BIVROST/360WebPlayer/blob/master/DEVELOPMENT.md).
