### ISSUE TITLE
Uncaught TypeError: Cannot read property 'canPlayType' of undefined

### ISSUE THREAD

**Issue by amerllica** [BIVROST/360WebPlayer#4]
Actually, after the new update to support `NativeHLS` on some devices like iOS devices, there is an error in playing HLS videos on all devices.

> Uncaught TypeError: Cannot read property 'canPlayType' of undefined

![Screen Shot 2020-12-29 at 11 50 17 AM](https://user-images.githubusercontent.com/10472437/103270004-526d8f80-49cc-11eb-81ae-77b07463feeb.png)

So it is crashing. Now I wanna send a PR for it. thanks.

**Comment by chanibal** [comment]
Thank you for the PR, no idea how I overlooked this. 

Merged, updated example site and release.
