### ISSUE TITLE
HLS video is felt in cross-origin error (The video element contains cross-origin data, and may not be loaded)

### ISSUE THREAD

**Issue by amerllica** [BIVROST/360WebPlayer#6]
I run a local server on my macOS and then expose it on its local IP, then I call my page on my android phone browser but the HLS video is not played and I see this error on my phone console:

> THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The video element contains cross-origin data, and may not be loaded.

![Screen Shot 2020-12-29 at 1 29 46 PM](https://user-images.githubusercontent.com/10472437/103276452-cfeccc00-49db-11eb-918e-a70916bad4e3.png)

It is my HTML code:
```html
<!DOCTYPE html>
<html>
<head>
    <title>pelk studio</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/cerulean/bootstrap.min.css" rel="stylesheet" />
    <link href="./bivrost.css" rel="stylesheet" />
    <script src="./bivrost-debug.js"></script>
    <script src="./hls.min.js"></script>
    <script type="text/javascript">
        Bivrost.verbose=true;
    </script>
</head>
<body >


<bivrost-player url="https://penaltyvr.com/stream/5f9b32a1e454a0dc5/playlist.m3u8"></bivrost-player>

<script type="text/javascript">
    var player;
    addEventListener("load", function() {
        player = document.getElementsByTagName("bivrost-player")[0].bivrost;
    });
</script>

</body>
</html>
```
And I call on my phone by using this address: `http://192.168.1.4:5000/testPage.html`

I guess this issue comes from `cross-origin` but the error appears just on mobile, not on desktop. when I call the above IP address on the desktop the video is shown but on Android phone I face this issue.

What does it mean and can we deal with this issue?

**Comment by chanibal** [comment]
Issue confirmed with native HLS on Android.  

This does not look like an issue with CORS headers, but something client side related. So even though it looks the same, [the documentation on CORS](https://github.com/BIVROST/360WebPlayer#video-does-not-work) does not apply here.

Will try to find the cause, or try to reenable HLS.js on platforms that support it failing back to native HLS as a last resort (it worked on iOS/MacOS, right?).

**Comment by amerllica** [comment]
Dear @chanibal, I fixed it with a simple check that uses NativeHLS just for iOS devices, actually, I tested new changes on many devices, when I add `isIOS` check then all devices even legacy Android and iOS could play a HLS video. let me send the PR. thanks for your time.

**Comment by chanibal** [comment]
Checking if this is iOS is a fix, but not the best one. HLS.js can decide if it supports the platform or not, this is a better way to test it. Im currently testing this fix. Thank you for the PR, but I don't think I'll be able to use it.

Also, some more obscure browsers exist that support HLS natively and have issues with HLS.js, for example Samsung Internet Browser (that means GearVR's) had this problem the last time I used it. This might fix issues with it, too.

**Comment by amerllica** [comment]
So do as what you want, By your description I think this PR is not good for this Player. but in my fork I should use it for our project. 

After our launch I wait for your update and then upgrade mine. thanks.
