### ISSUE TITLE
Pimax 5k+ FOV 200 degree

### ISSUE THREAD

**Issue by hgabor47** [BIVROST/360WebPlayer#8]
Hi,

Your work is very good. Grat! Thanks,
I use Pimax 5k+. The FOV greater than others, in the largest setup 200 degree. I use in 170 but in any case I can see black areas in the eyes corner. I think the headsets with smaller FOV working well. 
Can I increase the view globe area anywhere?

Thanks Gabor.

**Comment by chanibal** [comment]
Hi, I'm not sure why you have this issue, will need some additional information. 

1. Could you please verify if [WebXR demos](https://immersive-web.github.io/webxr-samples/) work correctly for you? 
2. What browser are you using?
3. What middleware are you using? SteamVR?
4. Where did you use the 360WebPlayer (please provide web address)? Did you try the [360WebPlayer demo page](https://tools.bivrost360.com/webplayer-docs/)?

**Comment by hgabor47** [comment]
> Hi, I'm not sure why you have this issue, will need some additional information.
> 
> 1. Could you please verify if [WebXR demos](https://immersive-web.github.io/webxr-samples/) work correctly for you?
> 2. What browser are you using?
> 3. What middleware are you using? SteamVR?
> 4. Where did you use the 360WebPlayer (please provide web address)? Did you try the [360WebPlayer demo page](https://tools.bivrost360.com/webplayer-docs/)?

**Comment by hgabor47** [comment]
> > 1. Could you please verify if [WebXR demos](https://immersive-web.github.io/webxr-samples/) work correctly for you?
**WebXR demos working well.**
> > 2. What browser are you using?
**Chrome with VR capability**
> > 3. What middleware are you using? SteamVR?
**SteamVR switched on before Chrome started**
> > 4. Where did you use the 360WebPlayer (please provide web address)? Did you try the [360WebPlayer demo page](https://tools.bivrost360.com/webplayer-docs/)?
**I use my local server but this phenomenon is appear in this 360WebPlayer demo page too**
